#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""CFFI bindings for libfprint"""

import os
from distutils.core import setup, Extension

setup(
    name="pyfprint-cffi",
    version="0.1",
    description="CFFI bindings for libfprint",
    author="Francisco Demartino",
    author_email="demartino.francisco@gmail.com",
    url="https://github.com/franciscod/pyfprint-cffi",
    license="GPL-2",
    packages=["pyfprint"],
    package_data={
        "pyfprint": [
            "freebl3.dll",
            "libcertdb.dll.a",
            "libcerthi.dll.a",
            "libcrmf.dll.a",
            "libcryptohi.dll.a",
            "libfprint.a",
            "libfprint.dll.a",
            "libfprint-0.dll",
            "libfreebl.dll.a",
            "libgcc_s_dw2-1.dll",
            "libgdk_pixbuf-2.0-0.dll",
            "libglib-2.0-0.dll",
            "libiconv-2.dll",
            "libintl-8.dll",
            "libjar.dll.a",
            "libnspr4.dll",
            "libnspr4.dll.a",
            "libnspr4_s.a",
            "libnss.dll.a",
            "libnss3.dll.a",
            "libnssb.dll.a",
            "libnssckfw.dll.a",
            "libnssdev.dll.a",
            "libnsspki.dll.a",
            "libnssutil.dll.a",
            "libnssutil3.dll.a",
            "libpixman-1-0.dll",
            "libpk11wrap.dll.a",
            "libpkcs12.dll.a",
            "libpkcs7.dll.a",
            "libpkixcertsel.dll.a",
            "libpkixchecker.dll.a",
            "libpkixcrlsel.dll.a",
            "libpkixmodule.dll.a",
            "libpkixparams.dll.a",
            "libpkixpki.dll.a",
            "libpkixresults.dll.a",
            "libpkixstore.dll.a",
            "libpkixsystem.dll.a",
            "libpkixtop.dll.a",
            "libpkixutil.dll.a",
            "libplc4.dll",
            "libplc4.dll.a",
            "libplc4_s.a",
            "libplds4.dll",
            "libplds4.dll.a",
            "libplds4_s.a",
            "libsectool.dll.a",
            "libsmime.dll.a",
            "libsmime3.dll.a",
            "libsoftokn.dll.a",
            "libsoftokn3.dll.a",
            "libssl.dll.a",
            "libssl3.dll.a",
            "libstdc++-6.dll",
            "libusb-1.0.dll",
            "libwinpthread-1.dll",
            "nss3.dll",
            "nssckbi.dll",
            "nssutil3.dll",
            "smime3.dll",
            "softokn3.dll",
            "ssl3.dll",
            "libp11-kit-0.dll",
            "libpcre-1.dll"
        ]
    },
    install_requires=[
        "cffi==0.8.6",
        "Pillow",
    ],
)
